Information:
  Title: writea
  Description: Writea is an open-source alternative for blogs, allowing for easy page configuration and ultimate flexibility.
  Link: github.com/prplwtf/writea
  Theme: Default

Connections:
  GitHub: prplwtf
  YouTube:
  Twitter: prplwtf
  Mastodon: ivy@quack.social