Information:
  Title: writea
  Icon: icon.png
  Description: Writea is an open-source alternative for blogs, allowing for easy page configuration and ultimate flexibility.
  Link: github.com/prplwtf/writea
  Theme: Default

Connections:
  GitHub: prplwtf
  GitLab: prplwtf
  Bluesky: prpl.wtf
  Twitter:
  Mastodon:
  Medium:
  Twitch:
  YouTube:
